# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=2000)),
                ('mailbox', models.CharField(max_length=2000)),
                ('type', models.CharField(max_length=2000)),
                ('whitelist_ip', models.CharField(max_length=2000)),
                ('inbox', models.CharField(max_length=2000)),
                ('outbox', models.CharField(max_length=2000)),
                ('host_url', models.CharField(max_length=2000)),
                ('server', models.CharField(max_length=2000)),
                ('customer', models.CharField(max_length=2000)),
            ],
        ),
    ]
